# Generated by Django 5.2.4 on 2025-09-10 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmbienteSENA', '0002_alter_instructor_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmbienteSENA.ambiente')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmbienteSENA.instructor')),
            ],
        ),
    ]
