# Generated by Django 5.2.4 on 2025-09-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmbienteSENA', '0003_ingreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingreso',
            old_name='fecha',
            new_name='fechaHoraEntrada',
        ),
    ]
