# Generated by Django 5.2.4 on 2025-09-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmbienteSENA', '0004_rename_fecha_ingreso_fechahoraentrada'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingreso',
            table='ingreso',
        ),
    ]
