# Generated by Django 5.2.4 on 2025-09-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmbienteSENA', '0005_alter_ingreso_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='fechaHoraSalida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
